spring:
  datasource:
    url: jdbc:mysql://localhost:3306/knowthenics_prod?useSSL=false&serverTimezone=UTC&useUnicode=yes&characterEncoding=utf8
    username: knowthenics_prod_user
    password: placeholder_for_real_prod_password
    platform: mysql
  #    initialization-mode: always  # Uncomment this line and create data-mysql.sql to initialize data
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
